---

######################
# Install Web Server #
######################

- name: Install Apache webserver
  hosts: all
  become: true
  gather_facts: true

  tasks:

  - name: Set hostname
    ansible.builtin.hostname:
      name: web-01
      use: systemd

  - name: Install Apache latest version i
    ansible.builtin.dnf:
      name: httpd
      state: latest

  - name: Apache enabled and running
    ansible.builtin.systemd:
      name: httpd
      enabled: true
      state: started

  - name: Copy personal index file
    ansible.builtin.copy:
      src: "files/index.html"
      dest: /var/www/html/index.html
      mode: '644'

  - name: Permit HTTP traffic
    ansible.posix.firewalld:
      service: http
      permanent: true
      immediate: true
      state: enabled

  - name: Deny HTTPS traffic
    ansible.posix.firewalld:
      service: https
      permanent: true
      immediate: true
      state: disabled


#####################
# Remove Web Server #
#####################

  - name: Remove Apache from webservers
    ansible.builtin.dnf:
      name: httpd
      state: absent
      autoremove: yes
    tags: ['delete','never']
